eval:
  metrics:
    - type: "recall_at_topk"
      k: null

  batch_size_per_gpu: 64

  local_verification:
    - func: one_of_one
      search_rank: 100
    - func: one_of_two
      search_rank: 10
    - func: one_of_four
      search_rank: 10
    - func: one_of_nine
      search_rank: 4
